#!/usr/bin/env python3
"""M5: the old Fragile Peace stylesheets, scoped under `.fp-doc` → campaign/site/campaign.css (ported from
Portents & Fortunes' scope_css.py, its M7).

The campaign's documents render inside the VTT's pages, whose own stylesheet defines some of the
same custom properties (--paper, --ink, --edge, --jade) and styles the same elements. Scoping
every rule to `.fp-doc` — the element each campaign document is drawn into — keeps the parchment
where it was and leaves the VTT's pages untouched: `:root`, `html` and `body` become `.fp-doc`
itself, every other selector a descendant of it. @media / @supports are scoped inside; @keyframes
and @font-face are copied as they are. Nothing but selectors changes.

    python3 campaign/source/scope_css.py

Sources: campaign/source/css/*.css, in the order below. Proves the output: every declaration block
of the sources appears in the output, the same number of times, and every output selector starts
with `.fp-doc`.
"""
import os
import re
import sys
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "css")
OUT = os.path.join(os.path.dirname(HERE), "site", "campaign.css")
# Each group of the old site's stylesheets, under the class campaign/site/site.js gives the documents that
# used them: the site's (512 pages; the map adds map.css) and each character dossier's own <style>, which
# loaded nothing else (check_docs.py proves the old pages' styles are these).
DOSSIERS = ["setsuna", "harunobu", "jujiro", "anzu"]
GROUPS = [(".fp-doc.fp-site", ["rokugan.css", "map.css"])] + \
         [(".fp-doc.fp-own-%s" % n, ["dossier-%s.css" % n]) for n in DOSSIERS]
SCOPE = ".fp-doc"   # every selector starts with it


def strip_comments(css):
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def blocks(css):
    """Top-level (prelude, body) pairs; body is the text between the matched braces."""
    out, i, n = [], 0, len(css)
    while i < n:
        j = css.find("{", i)
        if j < 0:
            if css[i:].strip():
                raise SystemExit("stray text: %r" % css[i:][:80])
            break
        depth, k = 1, j + 1
        while depth:
            if css[k] == "{":
                depth += 1
            elif css[k] == "}":
                depth -= 1
            k += 1
        out.append((css[i:j].strip(), css[j + 1:k - 1]))
        i = k
    return out


def scope_selector(sel, scope_to):
    sel = sel.strip()
    m = re.match(r"^(:root|html|body)\b(.*)$", sel)
    if m:
        return scope_to + m.group(2)
    if sel == "*":
        return scope_to + " *"
    return scope_to + " " + sel


def scope(css, decls, scope_to):
    out = []
    for pre, body in blocks(css):
        if pre.startswith("@media") or pre.startswith("@supports"):
            out.append(pre + "{\n" + scope(body, decls, scope_to) + "}")
        elif pre.startswith("@"):
            out.append(pre + "{" + body + "}")
        else:
            decls.append(body.strip())
            out.append(",".join(scope_selector(s, scope_to) for s in pre.split(",")) + "{" + body + "}")
    return "\n".join(out) + "\n"


def main():
    src_decls, text = [], []
    for scope_to, names in GROUPS:
        for name in names:
            css = strip_comments(open(os.path.join(SRC, name), encoding="utf-8").read())
            text.append("/* ── %s → %s ── */\n" % (name, scope_to) + scope(css, src_decls, scope_to))
    head = ("/* campaign/site/campaign.css — GENERATED by campaign/source/scope_css.py from campaign/source/css/;\n"
            "   do not edit by hand. Every rule is scoped to .fp-doc, the element a campaign document is drawn into. */\n")
    out = head + "\n".join(text)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(out)
    # proof
    got_decls, bad = [], 0

    def walk(css):
        nonlocal bad
        for pre, body in blocks(css):
            if pre.startswith("@media") or pre.startswith("@supports"):
                walk(body)
            elif not pre.startswith("@"):
                got_decls.append(body.strip())
                for s in pre.split(","):
                    if not s.strip().startswith(SCOPE):
                        bad += 1
                        print("UNSCOPED: %s" % s.strip())
    walk(strip_comments(out))
    if Counter(got_decls) != Counter(src_decls):
        bad += 1
        print("DECLARATIONS DIFFER")
    print("scope_css: %d rules from %d files → %s; every declaration block kept, every selector under %s: %s"
          % (len(got_decls), sum(len(n) for _, n in GROUPS), os.path.relpath(OUT, os.getcwd()), SCOPE, "OK" if not bad else "FAILED (%d)" % bad))
    sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
