#!/usr/bin/env python3
"""M5: a page of the old site as a document of the VTT's site tabs (campaign/PLAN.md F4, M5).

The old site was 517 pages under campaign/, each a full HTML page in one shell (build_site.shell): a nav
bar, the content, a footer. In the VTT the site is one page and the campaign's sections are its tabs
(campaign/site/site.js); each old page becomes a document, campaign/docs/<its old path>, drawn into a
`.fp-doc` element when its route is opened.

    document(path, html) -> the fragment       path is the page's old site-relative path ("chronicle/x.html")

What changes, and only this:
  - the page's <head>, its <nav class="topnav">, its <footer class="foot"> and its <script>s are dropped
    (the VTT supplies the frame; a page's script is a function the tab calls — campaign/site/);
  - every href/src is rewritten: a page → its route (#tab/path), an anchor on the page itself → the page's
    route with the anchor as its last segment, an asset → campaign/<path>, the player's page → gm/play.html.
Everything else is the page's own markup, byte for byte; check_docs.py proves the text identical and every
link resolving. build_site.py writes its pages through this; migrate_docs.py moved the hand-written ones once.
"""
import os
import re
from urllib.parse import unquote

# the old site's sections → the tabs (ids that do not collide with the VTT's own: characters, lore, …)
TAB = {'': 'fp', 'character': 'pcs', 'party': 'party', 'chronicle': 'chronicle',
       'dramatis-personae': 'personae', 'atlas': 'atlas', 'map': 'atlas', 'lore': 'rokugan', 'notes': 'notes'}
# the two old index pages that share the Atlas tab: the map is the tab itself, the gazetteer a path in it
SPECIAL = {'index.html': [], 'map/index.html': [], 'atlas/index.html': ['gazetteer']}

HREF_RE = re.compile(r'''((?:href|src)\s*=\s*)(["'])([^"']*)\2''')


def route(path, anchor=None):
    """The tab route of an old page ("lore/factions/crane-clan.html" → "#rokugan/factions/crane-clan")."""
    path = path.lstrip('/')
    top = path.split('/')[0] if '/' in path else ''
    if top not in TAB:
        raise ValueError('no tab for %s' % path)
    if path in SPECIAL:
        parts = list(SPECIAL[path])
    else:
        rest = path[len(top) + 1:] if top else path
        parts = [p for p in re.sub(r'(^|/)index\.html$', '', rest).split('/') if p]
        if parts:
            parts[-1] = re.sub(r'\.html$', '', parts[-1])
    if anchor:
        parts.append(anchor)
    return '#' + '/'.join([TAB[top]] + parts)


def target(page, ref):
    """An href/src on `page`, rewritten for a document drawn into the VTT's root page."""
    raw = ref
    ref = unquote(ref)
    if re.match(r'^(https?:|mailto:|data:|//)', ref):
        return raw
    if ref.startswith('#'):
        return route(page, ref[1:] or None)
    base, _, frag = ref.partition('#')
    t = os.path.normpath(os.path.join(os.path.dirname(page), base))
    if t.startswith('../'):                      # outside the site: the VTT's own pages, from the root
        return t[3:] + ('#' + frag if frag else '')
    if t.endswith('.html'):
        return route(t, frag or None)
    return 'campaign/' + t + ('#' + frag if frag else '')


def region(html):
    """The page's content: its <body>, less the nav bar, the footer and its scripts."""
    m = re.search(r'<body[^>]*>(.*)</body>', html, re.S)
    if not m:
        raise ValueError('no <body>')
    b = m.group(1)
    b = re.sub(r'<nav class="topnav">.*?</nav>', '', b, count=1, flags=re.S)
    b = re.sub(r'<footer class="foot">.*?</footer>', '', b, count=1, flags=re.S)
    b = re.sub(r'<script\b[^>]*>.*?</script>', '', b, flags=re.S)
    return b.strip() + '\n'


def document(page, html):
    return HREF_RE.sub(lambda m: m.group(1) + m.group(2) + target(page, m.group(3)) + m.group(2), region(html))


def write_manifest(docs):
    """campaign/docs/manifest.js: every document's path, so the tabs (campaign/site/site.js) can tell a
    route that names a document from one whose last segment is an anchor in it. Written by build_site.py
    after every build, and by migrate_docs.py."""
    import json
    paths = sorted(os.path.relpath(os.path.join(d, f), docs) for d, _, fs in os.walk(docs) for f in fs if f.endswith('.html'))
    with open(os.path.join(docs, 'manifest.js'), 'w', encoding='utf-8') as out:
        out.write('/* Generated by campaign/source/to_docs.py — every document under campaign/docs/. */\n'
                  'window.FP_DOCS = %s;\n' % json.dumps(paths, ensure_ascii=False))
    return len(paths)
